stages:
- review
- promote

# Test pipeline
publish-test:
  stage: review
  image: $REGISTRY/nomad:master
  script:
  # Set connection
  - "export NOMAD_ADDR=$NOMAD_ADDR_TEST"
  - "export NOMAD_TOKEN=$NOMAD_TOKEN_TEST"
  # Render deployment
  - render -deployment test.deployment.yaml -namespace $CI_PROJECT_NAMESPACE -name $CI_PROJECT_NAME > job.nomad
  # Create plan
  - (nomad plan job.nomad || eval $SET_NOMAD_RESULT)
  # Execute plan
  - nomad run job.nomad
  only:
  - master
  when: manual
  environment:
    name: review
    url: "http://$CI_PROJECT_PATH_SLUG.service.test-dc.consul/api/health/ready"
    on_stop: stop-test
  tags:
  - linux

stop-test:
  stage: review
  image: $REGISTRY/nomad:master
  variables:
    GIT_STRATEGY: none
  script:
  # Set connection
  - "export NOMAD_ADDR=$NOMAD_ADDR_TEST"
  - "export NOMAD_TOKEN=$NOMAD_TOKEN_TEST"
  # Stop job
  - "nomad stop $CI_PROJECT_PATH_SLUG"
  when: manual
  environment:
    name: review
    action: stop
  tags:
  - linux
  only:
  - master

# Promote to production
promote:
  stage: promote
  image: $REGISTRY/nomad:master
  script:
  # Set connection
  - "export NOMAD_ADDR=$NOMAD_ADDR_PROD"
  - "export NOMAD_TOKEN=$NOMAD_TOKEN_PROD"
  # Render deployment
  - render -deployment prod.deployment.yaml -namespace $CI_PROJECT_NAMESPACE -name $CI_PROJECT_NAME > job.nomad
  # Create plan
  - (nomad plan job.nomad || eval $SET_NOMAD_RESULT)
  # Execute plan
  - nomad run job.nomad
  only:
  - tags
  when: manual
  environment:
    name: production
    url: "http://$CI_PROJECT_PATH_SLUG.cloud.halykbank.nb/api/health/ready"
    on_stop: stop
  tags:
  - linux

stop:
  stage: promote
  image: $REGISTRY/nomad:master
  variables:
    GIT_STRATEGY: none
  script:
  # Set connection
  - "export NOMAD_ADDR=$NOMAD_ADDR_PROD"
  - "export NOMAD_TOKEN=$NOMAD_TOKEN_PROD"
  # Stop job
  - "nomad stop $CI_PROJECT_PATH_SLUG"
  when: manual
  environment:
    name: production
    action: stop
  tags:
  - linux
  only:
  - tags
